name: Build & Simulate

on: [push, pull_request]  # Trigger the workflow on push events

jobs:
  Simulate:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:

      - uses: actions/checkout@v4
      - name: Grant execute permission # just in case
        run: chmod +x gradlew

      - name: Build Robot Code
        run: ./gradlew build
    
      - name: Simulate Robot Code
        run: |
          timeout 60s ./gradlew simulateJava || exit_code=$?
          if [ $exit_code -eq 124 ]; then
            echo "Command exited with code 124, ignoring"
            exit 0
          else
            exit $exit_code
          fi